# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04e7e2e2a41c087971866e57193be3957e2008902c47e9890b1b686c3f9b37fac988fac0b07ce6fe3adb83241b8b5e15d417f20d08e57a6aa93ff4cb75bf86ae

test:
  secret_key_base: 9c8f6e55bebc629cb0d96b796cf5c65bb5df9c051e5e145810017e20fa360cf9f46a119a666db40d6c041fa0c98d2cf511d547b681aba6866b61ae469ae579f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
